name: Deployment

on:
  push:
    branches:
      - master

jobs:
  runTests:
    name: Run unit tests
  deployToAppengine:
    name: Deploy to appengine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build and deploy with Maven
        run: mvn clean package appengine:deploy --file pom.xml
